#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

NODE_DL="https://nodejs.org/en/download/"

cd "$DIR"

if [ -e "dist" ]; then
	echo "dist directory exists - exiting"
	exit 1
fi

if [ -e "dist.tgz" ]; then
	echo "dist.tgz exists - exiting"
	exit 1
fi

NODE_URL="$( /usr/bin/curl -L -s "$NODE_DL" | /usr/bin/grep darwin | /usr/bin/sed 's/.*"\(.*\)".*/\1/' )"

/bin/mkdir dist
cd dist

echo ""
echo "Downloading NodeJS from $NODE_URL..."
/usr/bin/curl -L -O "$NODE_URL"

echo ""
echo "Extracting NodeJS..."
FILE="$( echo "$NODE_URL" | /usr/bin/sed 's,.*/,,' )"
/usr/bin/tar xzf "$FILE"
/bin/rm -f "$FILE"

/bin/ln -s * node

echo ""
echo "Adding homebridge scripts..."
cd ..
/usr/bin/tar cf - homebridge | (cd dist; /usr/bin/tar xvf -)

echo ""
echo "Installing homebridge NodeJS modules..."
cd dist
./homebridge/installhomebridge

echo ""
echo "Adding ffmpeg symlink..."
cd homebridge
ln -s ../node/lib/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg .
cd ..

echo ""
echo "Clearing quarantine flags..."
/usr/bin/xattr -r -d com.apple.quarantine .

echo ""
echo "Creating distribution..."
/usr/bin/tar czf ../dist.tgz .

echo ""
echo "Done."
